name: Managed Connectors Cleanup
on:
  push:
    branches:
      - MGDOBR-1008test
jobs:
  run-managed-connectors-delete-script:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: "dev"
      - name: Free disk space
        uses: ./.github/actions/free-disk-space
      - name: Add mask
        run: |
          echo "::add-mask::${{ secrets.MANAGED_CONNECTORS_CONTROL_PLANE_URL }}"
      - name: Run Managed connector delete script
        env:
          MANAGED_CONNECTORS_CONTROL_PLANE_URL: ${{ secrets.MANAGED_CONNECTORS_CONTROL_PLANE_URL }}
        run: |
          ./.dev/bin/interaction/delete-managed-connectors.sh
